### ISSUE TITLE
Run lindemann -p 

### ISSUE THREAD

**Issue by Bo-Jin** [N720720/lindemann#263]
## 🐛 Bug Report

Hello, when I run the 'lindemann -p 459_02.lammpstrj' using the example in test/test_example,  it shows 'multiprocessing is implemented only for the -t flag' and doesn't have PDF file.

### Environment

* OS:  Linux 
* Python version, get it with: python 3.8, lindemann-0.4.0

### Screenshots
![图片](https://user-images.githubusercontent.com/23626945/126444126-3f6c8bf0-1c5b-4609-862e-728c3c8864cc.png)

**Comment by N720720** [comment]
Hey @Bo-Jin , 
thanks for your bug report and for trying the lindemann package. I apologize for working on your bug report so late. I hope you could use it with this limitation, at least for the ordinary calculation of the Lindemann index. I created this bug when I introduced multiprocessing. The bug is fixed now and I added more test, which I should have done earlier.
