### ISSUE TITLE
Looking forward to your reply(some questions)!

### ISSUE THREAD

**Issue by pppyk** [N720720/lindemann#267]
## Checklist

I ran your code, but there are still some questions, I hope you can help answer them, thank you.

## ❓ Question

1. Is the data in Figure 2 a rapid heating process?

2. Can you share the data in Figure 2?

3. For the last lindemann value output in the program, why is it divided by nframes and not divided by n-1

## 📎 Additional context
![BPW2NMS${KS6{A3Y() 0%XU](https://user-images.githubusercontent.com/71545635/130591559-ad14b8bb-6bc3-444f-b0a4-722be55ce1cc.png)

**Comment by Cloudac7** [comment]
It could be shown that <img src="http://www.sciweavers.org/tex2img.php?eq=%5Csigma_%7Bij%7D%5E2%3D%20%3C%20r_%7Bij%7D%5E2%20%3E%20-%20%3Cr_%7Bij%7D%3E%5E2&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0" align="center" border="0" alt="\sigma_{ij}^2= < r_{ij}^2 > - <r_{ij}>^2" width="176" height="28" />.

Well, from definition of Lindemann index, the upper term below the root symbol (i.e. `np.devide(array_var, nframes)`) is just a term yielding the variance of `r_ij` through the `nframes` according to Welford Algorithm, thus should be `nframes` instead of `N-1` in the original equation. 

However, there seems a bug in the original code yielding Lindemann index per frame, where `nframes` should be substituted into `iframe - 1` (i.e. number of frames from the first frame to current frame), for it would give wrong variance for each frame except the first (of course, 0) and the last one for it ignored the change of timescale. @N720720

**Comment by N720720** [comment]
Thanks for your contribution. I will look into it.

**Comment by N720720** [comment]
I added unit tests to reproduce this false behavior

**Comment by N720720** [comment]
> ## Checklist
> I ran your code, but there are still some questions, I hope you can help answer them, thank you.
> 
> ##  Question
> 1. Is the data in Figure 2 a rapid heating process?
> 2. Can you share the data in Figure 2?
> 3. For the last lindemann value output in the program, why is it divided by nframes and not divided by n-1
> 
> ##  Additional context
> ![BPW2NMS${KS6{A3Y() 0%XU](https://user-images.githubusercontent.com/71545635/130591559-ad14b8bb-6bc3-444f-b0a4-722be55ce1cc.png)

1. Yes, we are looking at a heating ramp with 50 thousand steps.
However, due care must be exercised, when one interprets such simulated phase
transitions. Since 50 thousand simulation steps can lead to the impression that in
fact we are looking at a slow process. Quite the opposite is the case since one
simulation step translates to 2 femtoseconds. Thus 50 thousand time steps portray
only a “real” time of 0.1 nanoseconds (given our timestep length). 
For a heating ramp that goes from 400K to 1200K this translates to a heating rate of 8 · 10<sup>12 </sup> K/s for 50 thousand steps. The heating rate is probably unrealistically fast, only comparable to a short intense laser impulse hitting a cluster, but the constraint lies here in the computational time and cost. 
To get a heating rate of 4 kelvin per second for a heating ramp difference of 800 kelvin 100 quadrillion (1 · 10<sup>17</sup> ) timesteps would be needed. With the actual simulation setup used, around 8 simulation steps
per second where calculated, this would take close to 4 · 10<sup>8</sup> years to calculate.

2. There are two 50k heating ramps of 459 Atoms clusters in the [folder](https://github.com/N720720/lindemann/tree/master/tests/test_example) for the unit tests. 

3. I fixed this in version 0.6.0
